#!/bin/bash -login 

#PBS -l walltime=48:00:00,nodes=1:ppn=1,mem=12gb
#PBS -N 1-quality-trim
#PBS -A ged
#PBS -M titus@idyll.org
#PBS -m abe

source $HOME/2014-mrnaseq-cloud/qsub/env.sh

module load FASTX

mocc_sra='SRR1197985 SRR1197986 SRR1199464 SRR1199259 SRR1199268'
mocu_sra='SRR1197522 SRR1197965 SRR1197972'
hyb_sra='SRR1198321 SRR1198337 SRR1198346'

cd $WORKDIR

for i in *_1.fastq
do 
    echo $i $(pwd)
    java -jar ~/Trimmomatic-0.33/trimmomatic-0.33.jar PE $i ${i/_1/_2} s1_pe s1_se s2_pe s2_se ILLUMINACLIP:$HOME/Trimmomatic-0.33/adapters/TruSeq3-PE.fa:2:30:10
    interleave-reads.py s1_pe s2_pe > ${i/_1/}.pe.fq
    cat s1_se s2_se > ${i/_1/}.se.fq
done

for i in *.pe.fq *.se.fq
do
    echo Filtering $i into ${i/fq/qc.fq}
    fastq_quality_filter -Q33 -q 30 -p 50 -i $i -o ${i/fq/qc.fq}
done

for i in *.pe.qc.fq
do
   extract-paired-reads.py $i
done

for i in *se.qc.fq
do
    cat $i >> ${i/se.qc.fq/pe.qc.fq.se}
done

mkdir mocc_reads mocu_reads hyb_reads
for i in $mocc_sra; do mv $i*.qc.fq.[ps]e mocc_reads;done
for i in $mocu_sra; do mv $i*.qc.fq.[ps]e mocu_reads;done
for i in $hyb_sra; do mv $i*.qc.fq.[ps]e hyb_reads;done
chmod a-w mocc_reads/*
chmod a-w mocu_reads/*
chmod a-w hyb_reads/*
