#!/bin/bash -login

#PBS -l walltime=168:00:00,nodes=1:ppn=8,mem=1000gb
#PBS -N 2-assemble-ocu-oases-raw
#PBS -A ged
#PBS -M titus@idyll.org
#PBS -m abe

source $HOME/2014-mrnaseq-cloud/qsub/env.sh

module load oases
module load velvet

OUTDIR=$WORKDIR-ocu
mkdir $OUTDIR
cd $OUTDIR
ln -fs $WORKDIR/mocu_reads/* .
paired=*.pe
single=*.se
velveth ${OUTDIR}/output 21,37,2 -fastq -shortPaired $paired -short $single
for((n=21;n<37;n=n+2));do velvetg ${OUTDIR}/output_"$n" -cov_cutoff auto -exp_cov auto -read_trkg yes -scaffolding no -ins_length 250; done
wait
for((n=21;n<37;n=n+2));do oases ${OUTDIR}/output_"$n"; done

qstat -f ${PBS_JOBID}

