#!/bin/bash -login

#PBS -l walltime=100:00:00,nodes=1:ppn=8,mem=100gb
#PBS -N 2-assemble-ocu-trinity-raw
#PBS -A ged
#PBS -M titus@idyll.org
#PBS -m abe

source $HOME/2014-mrnaseq-cloud/qsub/env.sh

module load screed
module load khmer/1.3
module load bowtie
module load trinity

OUTDIR=$WORKDIR-ocu-trinity
mkdir $OUTDIR
cd $OUTDIR

ln -fs $WORKDIR/mocu_reads/* .
for i in *.pe; do split-paired-reads.py $i;done
cat *.1 > left.fq
cat *.2 > right.fq
cat *.se >> left.fq
Trinity.pl --left left.fq --right right.fq --seqType fq -JM 64G --CPU 8

qstat -f ${PBS_JOBID}

