#!/bin/bash -login

#PBS -l walltime=100:00:00,nodes=1:ppn=8,mem=128gb
#PBS -N 3-dn-assemble-occ-trinity
#PBS -A ged
#PBS -M titus@idyll.org
#PBS -m abe

module load GNU/4.8.2
module load khmer/2.0

source $HOME/2014-mrnaseq-cloud/qsub/env.sh

h_table='mocc_hash.kh'
WKSP=$WORKDIR-dn-occ-oases

mkdir $WKSP
cd $WKSP

ln -fs $WORKDIR/mocc_reads/* .

normalize-by-median.py -p -C 20 -k 20 -N 4 -x 4e9 -s ${h_table} *.pe
normalize-by-median.py -C 20 -l mocc_hash.kh *.se
for i in *pe.keep; do split-paired-reads.py $i;done

module swap GNU/4.8.2 GNU
module load bowtie
module load trinity

cat *.1 > left.fq
cat *.2 > right.fq
wait
cat *single*keep >> left.fq
wait
Trinity.pl --left left.fq --right right.fq --seqType fq -JM 16G --CPU ${PBS_NUM_PPN}

qstat -f ${PBS_JOBID}

