#!/bin/bash -login

#PBS -l walltime=72:00:00,nodes=1:ppn=8,mem=128gb
#PBS -N 3-dn-assemble-occ-oases
#PBS -A ged
#PBS -M titus@idyll.org
#PBS -m abe

set -e

module load GNU/4.8.2
module load khmer/2.0

source $HOME/2014-mrnaseq-cloud/qsub/env.sh

h_table='mocc_hash.kh'
WKSP=$WORKDIR-dn-occ-oases

mkdir -p $WKSP
cd $WKSP

ln -fs $WORKDIR/mocc_reads/* .

normalize-by-median.py -p -C 20 -k 20 -N 4 -x 4e9 -s ${h_table} *.pe
normalize-by-median.py -C 20 -l mocc_hash.kh *.se
for i in *pe.keep; do extract-paired-reads.py $i;done

module swap GNU/4.8.2 GNU

module load oases
module load velvet

paired=*keep.pe
single=$(ls *keep.se *.se.keep)
velveth output 21,37,2 -fastq -shortPaired $paired -short $single
wait
for((n=21;n<37;n=n+2));do velvetg output_"$n" -cov_cutoff auto -exp_cov auto -read_trkg yes -scaffolding no -ins_length 250; done
wait
for((n=21;n<37;n=n+2));do oases output_"$n"; done

qstat -f ${PBS_JOBID}
