#!/bin/bash -login 

#PBS -l walltime=72:00:00,nodes=1:ppn=1,mem=64gb
#PBS -N assem_step1
#PBS -A ged-intel11
#PBS -M elijahlowe@gmail.com
#PBS -m abe                                                                                                                                                                                                     

module load screed
module load khmer
module load oases
module load velvet
module load SRAToolkit
module load FASTX

mocc_sra='SRR1197985 SRR1197986 SRR1199464 SRR119259 SRR1199268'
mocu_sra='SRR1197522 SRR1197965 SRR1197972'
hyb_sra='SRR1198321 SRR1198337 SRR1198346'
SRA_dir='ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByStudy/sra/SRP/SRP040/SRP040134/'

WKDR='/mnt/scratch/loweelij/mol_paper/'
mkdir $WKDR
cd $WKDR

wget -m ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByStudy/sra/SRP/SRP040/SRP040134/
#module load SRAToolkit or install SRAToolkit to extract the fastq files from SRA file
for i in ${SRA_dir}*/*.sra; do fastq-dump --split-files -F $i;done

for i in *_1.fastq
do 
    java -jar ~/Trimmomatic-0.30/trimmomatic-0.30.jar PE $i ${i/_1/_2} s1_pe s1_se s2_pe s2_se ILLUMINACLIP:/mnt/home/loweelij/Trimmomatic-0.30/adapters/TruSeq3-PE.fa:2:30:10
    interleave-reads.py s1_pe s2_pe > ${i/_1/}.pe.fq
    cat s1_se s2_se > ${i/_1/}.se.fq
done

for i in *.pe.fq *.se.fq
do
    echo Filtering $i into ${i/fq/qc.fq}
    fastq_quality_filter -Q33 -q 30 -p 50 -i $i -o ${i/fq/qc.fq}
done

for i in *.pe.qc.fq
do
   extract-paired-reads.py $i
done

for i in *se.qc.fq
do
    cat $i >> ${i/se.qc.fq/pe.qc.fq.se}
done

mkdir mocc_reads mocu_reads hyb_reads
for i in $mocc_sra; do mv $i*.qc.fq.[ps]e mocc_reads;done
for i in $mocu_sra; do mv $i*.qc.fq.[ps]e mocu_reads;done
for i in $hyb_sra; do mv $i*.qc.fq.[ps]e hyb_reads;done
