#!/bin/bash -login

#PBS -l walltime=72:00:00,nodes=1:ppn=4,mem=168gb
#PBS -N dn_ocu_oases
#PBS -A ged
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load screed
module load khmer/1.3
module load oases
module load velvet

WKDR='/mnt/scratch/loweelij/mol_paper/dn_ocu_oases_pytrim/'
mkdir $WKDR$(date +%Y%m%d)
cd $WKDR$(date +%Y%m%d)
ln -fs /mnt/scratch/loweelij/mol_paper/mocu_reads/* .
normalize-by-median.py -p -C 20 -k 20 -N 4 -x 4e9 -s mocu_tr_normC20k20.kh *paired*
wait
normalize-by-median.py -C 20 -k 20 -l mocu_tr_normC20k20.kh *single*
wait
paired=*paired*keep
single=*single*keep
velveth ${WKDR}output 21,37,2 -fastq -shortPaired $paired -short $single
wait
for((n=21;n<37;n=n+2));do velvetg ${WKDR}output_"$n" -cov_cutoff auto -exp_cov auto -read_trkg yes -scaffolding no -ins_length 250; done
wait
for((n=21;n<37;n=n+2));do oases ${WKDR}output_"$n"; done

qstat -f ${PBS_JOBID}

