#!/bin/bash -login

#PBS -l walltime=72:00:00,nodes=1:ppn=8,mem=32gb
#PBS -N dn_ocu_tri_pytrim
#PBS -A ged
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load screed
module load khmer/1.3
module load bowtie
module load trinity

WKDR='/mnt/scratch/loweelij/mol_paper/dn_ocu_tri_pytrim/'
mkdir $WKDR$(date +%Y%m%d)
cd $WKDR$(date +%Y%m%d)
ln -fs /mnt/scratch/loweelij/mol_paper/mocu_reads/* .
normalize-by-median.py -p -C 20 -k 20 -N 4 -x 4e9 -s mocu.kh *paired*
wait
normalize-by-median.py -C 20 -k 20 -l mocu.kh *single*
wait
for i in *paired.fq.keep; do split-paired-reads.py $i;done
wait
cat *.1 > left.fq
cat *.2 > right.fq
wait
cat *single*keep >> left.fq
wait
Trinity.pl --left left.fq --right right.fq --seqType fq -JM 16G

qstat -f ${PBS_JOBID}

