#!/bin/bash -login

#PBS -l walltime=96:00:00,nodes=1:ppn=8,mem=32gb
#PBS -N dn_occ_tri_pytrim
#PBS -A ged
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load screed
module load khmer/1.3
module load bowtie
module load trinity

h_tabele='mocc_hash.kh'
WKSP='/mnt/scratch/loweelij/mol_paper/dn_occ_tri_pytrim/'

mkdir $WKSP$(date +%Y%m%d)
cd $WKSP$(date +%Y%m%d)
ln -fs /mnt/scratch/loweelij/mol_paper/mocc_reads/* .
normalize-by-median.py -p -C 20 -k 20 -N 4 -x 4e9 -s mocc_hash.kh *paired*
wait
normalize-by-median.py -C 20 -l mocc_hash.kh *single*
wait
for i in *paired.fq.keep; do split-paired-reads.py $i;done
wait
cat *.1 > left.fq
cat *.2 > right.fq
wait
cat *single*keep >> left.fq
wait
Trinity.pl --left left.fq --right right.fq --seqType fq -JM 16G --CPU ${PBS_NUM_PPN}

qstat -f ${PBS_JOBID}

