#!/bin/bash -login

#PBS -l walltime=72:00:00,nodes=1:ppn=8,mem=64gb
#PBS -N raw_occ_tri_pytrim
#PBS -A ged
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load screed
module load khmer/1.3
module load bowtie
module load trinity

WKSP='/mnt/scratch/loweelij/mol_paper/raw_occ_tri_pytrim/'
mkdir $WKSP$(date +%Y%m%d)
cd $WKSP$(date +%Y%m%d)

ln -fs /mnt/scratch/loweelij/mol_paper/mocc_reads/* .
for i in *paired*; do split-paired-reads.py $i;done
wait
cat *.1 > left.fq
cat *.2 > right.fq
wait
cat *.single* >> left.fq
wait
Trinity.pl --left left.fq --right right.fq --seqType fq -JM 32G --CPU 8

qstat -f ${PBS_JOBID}

