ocu_dn_v<-read.table("/Users/elijahklowe/Desktop/Currently working on/manuscripts/figures/comp_paper/dist/Mocu_25_dn_trans_cd.fa.dist")
ocu_raw_v<-read.table("/Users/elijahklowe/Desktop/Currently working on/manuscripts/figures/comp_paper/dist/Mocu_29_raw_trans_cd.fa.dist")
ocu_vc_v<-read.table("/Users/elijahklowe/Desktop/Currently working on/manuscripts/figures/comp_paper/dist/Mocu_25_vc_trans_cd.fa.dist")
ocu_dn_t<-read.table("/Users/elijahklowe/Desktop/Currently working on/manuscripts/figures/comp_paper/dist/Mocu_Tri_dn_trans_cd.fa.dist")
ocu_raw_t<-read.table("/Users/elijahklowe/Desktop/Currently working on/manuscripts/figures/comp_paper/dist/Mocu_Tri_raw_trans_cd.fa.dist")
ocu_vc_t<-read.table("/Users/elijahklowe/Desktop/Currently working on/manuscripts/figures/comp_paper/dist/Mocu_Tri_vc_trans_cd.fa.dist")
ocu_reads<-read.table("/Users/elijahklowe/Desktop/Currently working on/manuscripts/figures/comp_paper/dist/Mocu_readsVreads.dist")

par(mfrow=c(1,1))

plot(ocu_dn_v$V1,cumsum(ocu_dn_v$V2)/34000000, type="l",xlim=c(0,30),ylim = c(0,1),xlab = "kmer count", ylab = "abundance",main="M. oculata distribution",yaxt="n")
#axis(2, at=pretty(returns), lab=paste(pretty(returns) * 100," %"), las=TRUE)
par(new = TRUE)
plot(ocu_raw_v$V1,cumsum(ocu_raw_v$V2)/34000000, type="l",xlim=c(0,30),ylim = c(0,1), xlab = "", ylab = "",lty=2,col="blue",yaxt="n",xaxt="n")
par(new = TRUE)
#plot(ocu_vc_v$V1,cumsum(ocu_vc_v$V2)/34000000, type="l",xlim=c(0,30),ylim = c(0,1),xlab = "", ylab = "",lty=3,col="green",yaxt="n",xaxt="n")
#par(new = TRUE)
plot(ocu_dn_t$V1,cumsum(ocu_dn_t$V2)/34000000, type="l",xlim=c(0,30),ylim = c(0,1),xlab = "kmer count",lty=1, col="green",ylab = "",xaxt="n")
par(new = TRUE)
plot(ocu_raw_t$V1,cumsum(ocu_raw_t$V2)/34000000, type="l",xlim=c(0,30),ylim = c(0,1), xlab = "", ylab = "",lty=5,col="red",yaxt="n",xaxt="n")
#par(new = TRUE)
#plot(ocu_vc_t$V1,cumsum(ocu_vc_t$V2)/34000000, type="l",xlim=c(0,30),ylim = c(0,1),xlab = "", ylab = "",lty=6,col="red",yaxt="n")
legend(0,0.9, c("DN V/O","Raw V/O", "DN T", "Raw T"), cex=0.8, col=c("black","blue","green","red"), lty=c(1,2,1,5),lwd=2, bty="n")